// Sample news data
const newsData = [
    {
        image: './Images/icia2.jpg',
        title: 'Abstract submission deadline for ICIA 2023 extended',
        content: 'The annual meeting of the International Conference on Scientific Advancement (ICIA) is scheduled to be held by the Islamic University of Maldives (IUM) this year as well May 6, 2023 and May 7, 2023.\nThis conference, that will be held for a total of 2 (two) days, is the most ambitious conference to ever be hosted by IUM.\n The deadline for submission of abstracts for ICIA 2023 has been extended to February 25, 2023.\n Additionally, the papers are open to submission in English, Dhivehi, and Arabic.\nRegistration for paper presentations at the conference is available through the conference website www.icia.mv.',
    },
    {
        image: './Images/icia1.jpg',
        title: 'IUM research conference starts next Saturday',
        content: 'The Islamic University of Maldives (IUM) will host its annual International Conference on Intellectual Advancement (ICIA) conference on coming Saturday and Sunday.\nThis is one of the largest international research conferences held in the country. The conference will mainly feature presentations of research papers and panel discussions.\nIn addition, there will be a keynote speech at the opening ceremony of each day. One of the keynote topics is Artificial Intelligence in Higher Education: Challenges and Possibilities. The other topic is Language and Societal Development in the Dhivehi Writings of Hussain Salahuddeen.\nA total of 223 researchers will present 52 papers at the conference. Topics include halal tourism, Islamic finance, womens health, psychology, literature, financial system, and youth. Papers will be presented in a total of three languages: Dhivehi, Arabic, and English.\nThis years conference is sponsored by Maldives Pension Office, STELCO, Ooredoo, Dhiraagu, IIIT, Maldives Islamic Bank, and Amana Takaful.\nThe conference was launched in 2016 with the aim of building a society that loves to share knowledge and learn. Due to the coronavirus, 2020 and 2021 were held in a hybrid format. After that, in 2022, it has been continued to hold the conference physically as before.',
    },
    {
        image: './Images/dhiyaresvcnews.jpg',
        title: 'Regarding the article on Dhiyares news regarding the claims that the Vice-Chancellor of the Islamic University of Maldives has asked the IUM Student Union to campaign for the President',
        content: 'The statement that Vice Chancellor Dr. Ibrahim Zakariyya Moosa has asked the students of the Universitys Students Union and asked them to campaign for President Ibrahim Mohamed Solih in the presidential election is without a doubt fabricated.\nThe meeting conducted between these two parties in the presence of the Student Dean was about Adhabee Gulzaaru event, organized by IUMSU and the preparations for the said event. During this 1-hour-long meeting, Vice Chancellor Dr. Ibrahim Zakariyya Moosa not only discussed the event but also advised the students to refrain from actively taking part in any political activity as it goes against the disciplines and values of being a student.\n After the meeting, VC initiated the jersey handover and inducement for the IUM Futsal Team (Mens) playing in the MNU Futsal Tournament. Discussions on how to inspire interest in sports amongst students were also carried out afterwards.\n While the University also denies the article in "Dhiyares" newspaper that the Vice-Chancellor instructed the students union members to campaign for a certain person in the presidential election, the University reminds that journalism should be done responsibly. We also urge not to provide news to the people without obtaining the true information.\n We strongly condemn the false statement and misinterpretation made about the meeting between the vice-chancellor of the Islamic University of Maldives, Dr. Ibrahim Zakariyya Moosa, and the Students Union of this IUM and commend not to repeat such acts of defamation.'
        
    },
    {
        image: './Images/convocation2023.jpg',
        title: 'Islamic University of Maldives 7th Convocation Ceremony',
        content: 'The 07th Graduation Ceremony of the Islamic University of Maldives was held today, 25 May 2023, in sessions.\nAwards and certificates were presented to the students who graduated from Islamic University in 2022.\n The first session of the 07th graduation ceremony of the Islamic University of Maldives was graced by the former Minister of Education, Dr. Mahmoud Shauqi and the second session was graced by the Honorable President of the Republic of the Maldives, President Ibrahim Mohamed Solih. In addition to the distinguished guests, the ceremony was attended by members of the university council, alumnus of the university, students and their parents.\nIn the year 2022, 706 students have graduated from Islamic University of Maldives. 174 students at certificate level, 119 students at masters level, 79 students at postgraduate diploma level, 211 students at degree level, 118 students at diploma level, and 5 students at associate degree level were given their respected certificates.\nFurthermore, this year, a total of 9 students received the Best Student Award, one of the most prestigious awards granted during the convocation.\nThese awards were presented to the deserving prizewinners during the night session of 7th convocation of IUM held on 25th May 2023, Thursday by the Guest of Honor, President Ibrahim Mohamed Solih. The winners of the Best Students Award 2022 are as follows.\n 1. Bushra Abdul Latif / Kuredhivaru, N. Kudafari Postgraduate Diploma in Teaching, Kulliyya of Education\n  2. Ali Arif/ Saheemivilla, R. Hulhudhuffaaru Master of Teaching and Learning, Kulliyya of Education\n 3. Maryam Anees / Miskiymagu. Maaveyge, Gn. Fuvahmulah  Bachelor of Education (Primary), Kulliya of Education\n 4. Aishath Ahla / Ethumaage, B. Eydhafushi Bachelor of Teaching Arabic Language, Kulliya of Education\n5. Aminath Mohamed / Maavaidhooge, Hd. Nolhivaranfaru  Bachelor of Teaching Islamic Studies, Kulliyya of Education\n 6. Hafeeza Abdul Sattar / Maathoda avah. Mushtareege, Gd. Faresmaathoda Master of Arts in Journalism and Media Communications, Kulliyya of Islamic Revealed Knowledge and Human Sciences\n 7. Abdul Rahman Yunus / Maza, R. Alifushi - Master of Qiraat, Kulliya of Quran and Sunnah\n 8. Abdul Ghani Mohamed / H. Hostside, Male Master of Islamic Judicial Sciences and Sharia Policy, Kulliya of Sharia and Law\n 9. Nazneen Abdul Sattar / Lainoofarumaage, Gd. Hodehdhoo Diploma in Arabic Language, Kulliya of Arabic Language.'

    },
    {
        image: './Images/vc transition.jpg',
        title: 'Regarding the article on Dhiyares News stating that the Vice Chancellor of Islamic University of Maldives refused to meet the Transitional Committee ',
        content:'The Islamic University of Maldives would like to elucidate the misleading claims that the Vice Chancellor of IUM declined the Transitional Committees meeting.We would like to clarify that on Tuesday, October 10, 2023, at 9:00 am, the Transitional Committees meeting with IUM had, in fact, had taken place, with the Chancellor and some members of senior management in attendance.\n The absence of Vice Chancellor in this meeting is by no means due to any ill intention but due to a previously arranged commitment.And on this note, we would like to point out that Vice Chancellor gave upmost prominence on fully providing the requested information and corporation to the Transitional Committee.\n Hence, it can be only concluded that the article published in the Dhiyares News purported to mislead the readers with false allegations yet again. Thus we repeatedly insist that these acts of defamations be stopped and to do your duty as journalists responsibly.'
    },
   
  ];
