# Generated by Django 4.2.5 on 2023-10-05 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_program_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='departmant',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
