# Generated by Django 4.2.5 on 2023-10-04 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='section',
            table='section',
        ),
    ]
