# Generated by Django 3.2.20 on 2023-10-23 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_auto_20231022_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topmanagement',
            name='image',
        ),
    ]
