# Generated by Django 3.2.20 on 2023-10-23 10:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_remove_topmanagement_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='topmanagement',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
    ]
