# Generated by Django 3.2.20 on 2023-10-23 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_topmanagement_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topmanagement',
            name='image',
        ),
    ]
