# Generated by Django 3.2.20 on 2023-10-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_topmanagement_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topmanagement',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
