# Generated by Django 4.2.5 on 2023-10-26 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0015_hrmd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gazette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('date', models.DateField(max_length=30)),
                ('attachment', models.FileField(upload_to='files')),
                ('image', models.ImageField(upload_to='images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'gazette_doc',
            },
        ),
    ]
