# Generated by Django 4.2.5 on 2023-10-27 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0020_annualreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='RulesRegulations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('attachment', models.FileField(upload_to='files')),
                ('image', models.ImageField(upload_to='images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'rules_regulations_doc',
            },
        ),
    ]
