# Generated by Django 4.2.5 on 2023-10-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0022_collaborators'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmant', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'contact_us_doc',
            },
        ),
        migrations.RenameField(
            model_name='collaborators',
            old_name='Signed',
            new_name='signed',
        ),
    ]
