# Generated by Django 4.2.5 on 2023-10-28 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0023_contactus_rename_signed_collaborators_signed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='departmant',
            new_name='department',
        ),
    ]
